# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=30, verbose_name='Titular / Razon Social')),
                ('comercio', models.CharField(max_length=30)),
                ('domicilio', models.CharField(max_length=30)),
                ('cuit', models.CharField(max_length=30, verbose_name='CUIT')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Dicembre')], max_length=30)),
                ('anio', models.CharField(default=2017, max_length=4)),
                ('fecha', models.DateField()),
                ('nfactura', models.CharField(max_length=30)),
                ('tipo', models.CharField(default='C', max_length=2)),
                ('ing_porcentaje', models.IntegerField(default=0, verbose_name='Importe Neto Gravado (%)')),
                ('ing', models.IntegerField(default=0, verbose_name='Importe Neto Gravado')),
                ('cng', models.IntegerField(default=0, verbose_name='Conceptos No Gravados')),
                ('op_ex', models.IntegerField(verbose_name='Operaciones Exentas')),
                ('iva_liq', models.IntegerField(default=0, verbose_name='IVA Liquidado')),
                ('iva_rec', models.IntegerField(default=0, verbose_name='IVA Recargo N/I')),
                ('total_fac', models.IntegerField(verbose_name='TOTAL Facturado')),
                ('cred_fisc', models.IntegerField(default=0, verbose_name='Cred. Fiscal N/Creditos')),
                ('ret_perc', models.IntegerField(default=0, verbose_name='Retenciones / Percepciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=30)),
                ('cuit', models.CharField(max_length=30, verbose_name='CUIT')),
                ('nombre_fantasia', models.CharField(max_length=30)),
                ('iva', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('M', 'Monotributista'), ('E', 'Excento'), ('CF', 'Consumidor Final')], max_length=30, verbose_name='IVA')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.Proveedor'),
        ),
    ]
