# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0002_auto_20170614_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('cuit', models.CharField(max_length=30, verbose_name='CUIT')),
                ('es_cliente', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('iva', models.CharField(choices=[('CF', 'Consumidor Final'), ('I', 'Inscripto'), ('NI', 'No Inscripto'), ('M', 'Monotributo'), ('E', 'Excento')], max_length=30, verbose_name='Categoría de IVA')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('propietario', models.CharField(max_length=30)),
                ('cuit', models.CharField(max_length=30, verbose_name='CUIT')),
                ('localidad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('directorio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_libro', models.CharField(choices=[('V', 'Libro Ventas'), ('C', 'Libro Compras')], max_length=1, verbose_name='Tipo de Libro')),
                ('fecha', models.DateField()),
                ('tipo_comprobante', models.CharField(choices=[('F', 'Factura'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('R', 'Recibo')], max_length=2, verbose_name='Tipo de comprobante')),
                ('nfactura', models.CharField(max_length=30)),
                ('alic', models.IntegerField(default=0, verbose_name='Alic.')),
                ('importe', models.IntegerField(verbose_name='Importe Neto')),
                ('ex_iva_insc', models.IntegerField(default=0, verbose_name='Exento IVAS Insc.')),
                ('ex_19640', models.IntegerField(default=0, verbose_name='Exento 19640 IVA No Insc')),
                ('ret', models.IntegerField(default=0, verbose_name='Retención Internos')),
                ('cli_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.CliPro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.Empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='detallelibro',
            name='encabezado',
        ),
        migrations.RemoveField(
            model_name='detallelibro',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='encabezadolibro',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleLibro',
        ),
        migrations.DeleteModel(
            name='EncabezadoLibro',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
