# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0003_auto_20170830_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_comprobante', models.CharField(choices=[('F', 'Factura'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('R', 'Recibo')], max_length=2, verbose_name='Tipo de comprobante')),
                ('nfactura', models.CharField(max_length=30)),
                ('alic', models.IntegerField(default=0, verbose_name='Alic.')),
                ('importe', models.IntegerField(verbose_name='Importe Neto')),
                ('ex_iva_insc', models.IntegerField(default=0, verbose_name='Exento IVA Insc.')),
                ('ex_19640', models.IntegerField(default=0, verbose_name='Exento 19640 IVA No Insc')),
                ('ret', models.IntegerField(default=0, verbose_name='Retención Internos')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='alic',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='cli_pro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='ex_19640',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='ex_iva_insc',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='nfactura',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='ret',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='tipo_comprobante',
        ),
        migrations.AlterField(
            model_name='clipro',
            name='iva',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('I', 'Inscripto'), ('NI', 'No Inscripto'), ('M', 'Monotributo'), ('E', 'Exento')], max_length=30, verbose_name='Categoría de IVA'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='cli_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.CliPro'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.Libro'),
        ),
    ]
