# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0005_auto_20171002_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together=set([('empresa', 'tipo_libro')]),
        ),
    ]
