# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0006_auto_20171003_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='alic',
            field=models.IntegerField(default=0, null=True, verbose_name='Alic.'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cli_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.CliPro'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='ex_19640',
            field=models.IntegerField(default=0, null=True, verbose_name='Exento 19640 IVA No Insc'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='ex_iva_insc',
            field=models.IntegerField(default=0, null=True, verbose_name='Exento IVA Insc.'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='importe',
            field=models.IntegerField(null=True, verbose_name='Importe Neto'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='nfactura',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='ret',
            field=models.IntegerField(default=0, null=True, verbose_name='Retención Internos'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tipo_comprobante',
            field=models.CharField(choices=[('F', 'Factura'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('R', 'Recibo')], max_length=2, null=True, verbose_name='Tipo de comprobante'),
        ),
        migrations.AlterUniqueTogether(
            name='detalle',
            unique_together=set([('libro', 'tipo_comprobante', 'nfactura')]),
        ),
    ]
