# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0007_auto_20171005_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='alic',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='ex_19640',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='ex_iva_insc',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='ret',
        ),
        migrations.AddField(
            model_name='detalle',
            name='gravado',
            field=models.IntegerField(default=0, null=True, verbose_name='Gravado'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='imp_int',
            field=models.IntegerField(default=0, null=True, verbose_name='Imp. Internos'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='iva105',
            field=models.IntegerField(default=0, null=True, verbose_name='I.V.A. 10,5%'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='iva21',
            field=models.IntegerField(default=0, null=True, verbose_name='I.V.A. 21%'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='iva_otros',
            field=models.IntegerField(default=0, null=True, verbose_name='Otros I.V.A.'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='letra',
            field=models.CharField(max_length=1, null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='no_gravado',
            field=models.IntegerField(null=True, verbose_name='No Gravado'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='otros',
            field=models.IntegerField(default=0, null=True, verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='ret_IVA',
            field=models.IntegerField(default=0, null=True, verbose_name='Ret. I.V.A.'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='ret_iibb',
            field=models.IntegerField(default=0, null=True, verbose_name='Ret. IIBB'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='rg2126',
            field=models.IntegerField(default=0, null=True, verbose_name='R.G. 2126'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='sucursal',
            field=models.CharField(max_length=3, null=True, verbose_name='Suc'),
        ),
        migrations.AlterField(
            model_name='clipro',
            name='cuit',
            field=models.CharField(max_length=30, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='clipro',
            name='iva',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('I', 'Inscripto'), ('NI', 'No Inscripto'), ('M', 'Monotributo'), ('E', 'Exento')], max_length=30, verbose_name='Tipo I.V.A.'),
        ),
        migrations.AlterField(
            model_name='clipro',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='nfactura',
            field=models.CharField(max_length=30, null=True, verbose_name='N°'),
        ),
    ]
