# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-07 08:36
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IVAcompras', '0009_auto_20171019_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipro',
            name='cuit',
            field=models.CharField(max_length=13, unique=True, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='clipro',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cli_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IVAcompras.CliPro', verbose_name='Cliente/Proveedor'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gravado'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='imp_int',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Imp. Internos'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='iva105',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='I.V.A. 10,5%'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='iva21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='I.V.A. 21%'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='iva_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Otros I.V.A.'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='no_gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='No Gravado'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='ret_IVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ret. I.V.A.'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='ret_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ret. IIBB'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='rg2126',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='R.G. 2126'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='sucursal',
            field=models.CharField(max_length=3, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tipo_comprobante',
            field=models.CharField(choices=[('F', 'Factura'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('R', 'Recibo')], max_length=2, null=True, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=13, unique=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='detalle',
            unique_together=set([('libro', 'tipo_comprobante', 'nfactura', 'letra')]),
        ),
    ]
